version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Civar.Api/Dockerfile
    container_name: civar-api
    ports:
      - "5217:8080"
    environment:
      - ConnectionStrings__DefaultConnection="Host=civardb.postgres.database.azure.com;Database=postgres;Username=civaradmin;Password=kanserpsi125*;Port=5432;Ssl Mode=Require;Trust Server Certificate=true;"
      - REDIS_CONNECTION=civarredis.redis.cache.windows.net:6380,password=tYDDVq4q9pFWMc7qbm8o6rl37iG41BMapAzCaOpwP7g=,ssl=True,abortConnect=False
      - RabbitMQ__Host=goose.rmq2.cloudamqp.com
      - RabbitMQ__User=ajrpcmix
      - RabbitMQ__Pass=5AyfxZ-p05C2HZpEF7AUlhBAtzCztL9_
      - RabbitMQ__VHost=ajrpcmix
      - JwtSettings__Key=6+j4GJ6&3-s5{^f))=duf7432JHFDSKAJFHK887+897579SJKHF8471/*-dsahfyr5hK)34F*&K3HFG&*eeg*IR6HY???((1
    depends_on:
      - db
      - rabbitmq

  frontend:
    build:
      context: ./civar-frontend
      dockerfile: Dockerfile
    container_name: civar-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1461
      POSTGRES_DB: CivarDb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db-data:
